### ISSUE TITLE
Add build-tags to README.md

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss-engine#1]
Add tags to the beginning of README.md for travis, codecov.io and coverity similar to the tpm2-tss project.

- travis is looking good.
- codecov.io is lacking and icon or I could not find it yet. Also needs access grant by tpm2-software admin first
- coverity needs access grant by tpm2-software admin

**Comment by AndreasFuchsSIT** [comment]
Travis and codecov are in since aeabe1c.

Coverity seems to have some problems for the moment.

**Comment by AndreasFuchsSIT** [comment]
@flihp : Could you check this project into coverity please ?

**Comment by flihp** [comment]
We've talked about this a few times already: I can't get the coverity UI to pick up *any* of the projects in the tpm2-software github org either so we're having the same issue with the PKCS#11 library currently.
@williamcroberts: when you reach out to coverity support can you please include this repo in your request?

**Comment by AndreasFuchsSIT** [comment]
I know, I thought someone had already asked them. @williamcroberts when do you plan on asking them ?
P.S. I've also asked them on August 30th, but no response yet...

**Comment by williamcroberts** [comment]
@flihp I'll try today. Sorry I was away for a few days

**Comment by AndreasFuchsSIT** [comment]
Still stale because travis...
Removing from milestone plan unfortunately...

**Comment by AndreasFuchsSIT** [comment]
Fixed with 3029c2c37d9d393f32e4c3f311f03379dab83618
