### ISSUE TITLE
How to use key with Owner Auth? Setting Owner Auth via Engine Ctrl does not work 

### ISSUE THREAD

**Issue by RaymWong** [tpm2-software/tpm2-tss-engine#105]
Hi,
I have tried to set the owner auth value via engine, but use of the key created with owner auth still not working.  How to set Owner Auth value for the key created?

Step1: Working OK
echo 123 > mydata
tpm2_changeauth -o owner123 -e endorsement123 -l lockout123
tpm2tss-genkey -a rsa rsa2.tss -o owner123
openssl rsa -engine tpm2tss -inform engine -in rsa2.tss -pubout -outform pem -out rsa2.pub
openssl pkeyutl -pubin -inkey rsa2.pub -in mydata -encrypt -out mycipher

Step2: Failed at decrypttion with  authurization failed 0x9a2 
openssl engine -pre SET_OWNERAUTH:owner123 tpm2tss
openssl pkeyutl -engine tpm2tss -keyform engine -inkey rsa2.tss -decrypt -in mycipher -out mydata_decode

**Comment by AndreasFuchsSIT** [comment]
AFAIK none of the openssl engine cli commands supports setting of engine controls (besides openssl engine with -pre and -post).

You can use the ENGINE_ctrl from your own application but not command line.

If you set something with `openssl engine` it is of course lost during the next call to `openssl pkeyutl` I'm afraid... But that's how `openssl` works to my understanding...

**Comment by longntv** [comment]
@RaymWong :
I got same problem, and I did workaround as set password into environment and load when openssl call tpm2tss engine
1) add the below code before function call Esys_TR_SetAuth in init_tpm_parent function of tpm2-tss-engine-common.c 
    
`// get password from environtment variable
    char*pass = getenv("TPM2_OWNER_AUTH");
    if(pass != NULL )
    {
        DBG("Setting owner auth from environtment variable.\n");
        ownerauth.size = strlen((char *)pass);
        memcpy(&ownerauth.buffer[0], pass, ownerauth.size);
    }
    else
    {
        DBG("Password is empty.\n");
    }` 
2) before run openssl with tpm2tss engine set password to environment variable:
`export TPM2_OWNER_AUTH=password`

Hope this helps

**Comment by AndreasFuchsSIT** [comment]
The intended way of doing this is to set the ownerpassword for the engine via an openssl config file.

The env variable was intended mainly for testing purposes and I was hoping to get rid of it at some point.

**Comment by RaymWong** [comment]
> @RaymWong :
> I got same problem, and I did workaround as set password into environment and load when openssl call tpm2tss engine
> 
> 1. add the below code before function call Esys_TR_SetAuth in init_tpm_parent function of tpm2-tss-engine-common.c
> 
> `// get password from environtment variable char*pass = getenv("TPM2_OWNER_AUTH"); if(pass != NULL ) { DBG("Setting owner auth from environtment variable.\n"); ownerauth.size = strlen((char *)pass); memcpy(&ownerauth.buffer[0], pass, ownerauth.size); } else { DBG("Password is empty.\n"); }`
> 2) Rebuild and make install / Or copy libtpm2tss.so and libtpm2tss.la into your engines lib folder
> 3) before run openssl with tpm2tss engine set password to environment variable:
> `export TPM2_OWNER_AUTH=password`
> 
> Hope this helps

Many thanks for your advice.

**Comment by RaymWong** [comment]
> The intended way of doing this is to set the ownerpassword for the engine via an openssl config file.
> 
> The env variable was intended mainly for testing purposes and I was hoping to get rid of it at some point.

Is this method currently working? or still need to be implemented? Thanks.

**Comment by longntv** [comment]
Hi @RaymWong 

I'm not verify but I think it's working with config SET_OWNERAUTH

`[tpm2tss_section]
engine_id = tpm2tss
dynamic_path = /usr/lib/engines-1.1/libtpm2tss.so
default_algorithms = RSA,ECDSA
init = 1
#SET_TCTI = <TCTI_options>
#SET_OWNERAUTH = <could_set_password_here, but then it's readable>
#SET_PARENTAUTH = <password_of_parent_key> `

The sample configuration here
[(https://github.com/tpm2-software/tpm2-tss-engine/blob/master/openssl.conf.sample)]

To change openssl config: `export OPENSSL_CONF=/path/to/openssl-tpm.cnf`

**Comment by AndreasFuchsSIT** [comment]
Yep
