### ISSUE TITLE
PEM file incompatibilty

### ISSUE THREAD

**Issue by dwmw2** [tpm2-software/tpm2-tss-engine#11]
@jejb already had a TPM2 engine at https://git.kernel.org/pub/scm/linux/kernel/git/jejb/openssl_tpm2_engine.git/ since last year.

This new engine seems to store wrapped keys in a different format. And has a different engine name. So code which attempts to use one engine, for example like this: http://git.infradead.org/users/dwmw2/openconnect.git/commitdiff/7edab6c6c ..., isn't going to work with the other engine.

Please resolve this, and document the storage format.

**Comment by AndreasFuchsSIT** [comment]
That's true.
Different project come up with different formats.

However, I cannot look at the other codebase (GPL) for tainting this codebase's license (BSD).
Could you describe the other engine's storage format ?

**Comment by dwmw2** [comment]
It still uses the format discussed in https://mta.openssl.org/pipermail/openssl-dev/2016-December/008936.html

**Comment by AndreasFuchsSIT** [comment]
#22 introduced the new "joined" PEM format
