### ISSUE TITLE
openssl req: CSR creating asking for password when none is required

### ISSUE THREAD

**Issue by dnoliver** [tpm2-software/tpm2-tss-engine#156]
Similar to the problem described in https://github.com/tpm2-software/tpm2-tss-engine/blob/46074881bd8adba96eb35d9e630db9988ea9259d/test/rsasign_persistent_emptyauth.sh#L38:L44, but with tpm-tss-2.3.1

Need to wrap `openssl req` with an expect script that pass an empty password

Versions:

1. Fedora Server 31
2. Tpm2-tools-4.0.1-1.fc31.x86_64
3. Tpm2-tss-2.3.1-1.fc31.x86_64
4. Openssl-1-1.1d-2.fc31.x86_64
5. In kernel tpm resource manager (tpmrm), kernel version is 5.4.7-200.fc31.x86_64
6. Latest master version of tpm2-tss-engine

To reproduce:

```text
# Clear the TPM
tpm2_clear

# Create Endorsement Key
tpm2_createprimary -c ek.ctx -C e
tpm2_readpublic -c ek.ctx -o ek.pub > ek.yaml
cat ek.yaml | grep '^name:' | awk '{ print $2 }' > ek.name

# Create Private Enrollment Key
tpm2_create -C ek.ctx -G ecc:ecdsa -g sha256 -u key.pub -r key.priv -a 'sign|fixedtpm|fixedparent|sensitivedataorigin|userwithauth'
tpm2_load -C ek.ctx -u key.pub -r key.priv -c key.ctx
tpm2_evictcontrol -C o -c key.ctx 0x817FFFFF
tpm2_readpublic -c key.ctx > key.yaml
cat key.yaml | grep '^name:' | awk '{ print $2 }' > key.name

# Generate the Certificate Signing Request
echo "[ req ]" > csr.cnf
echo "default_bits = 2048" >> csr.cnf
echo "distinguished_name = req_distinguished_name" >> csr.cnf
echo "prompt = no" >> csr.cnf
echo "[ req_distinguished_name ]" >> csr.cnf
echo "C = US" >> csr.cnf
echo "ST = Oregon" >> csr.cnf
echo "L = Hillsboro" >> csr.cnf
echo "O = Intel Corp" >> csr.cnf
echo "OU = Internet of Things Group" >> csr.cnf
echo "CN = test@intel.com" >> csr.cnf
openssl req -new -key 0x817FFFFF -engine tpm2tss -keyform engine -out key.csr -config csr.cnf
```

To workaround wrap openssl call with an expect script:

```text
expect << EOF
  spawn openssl req -new -key 0x817FFFFF -engine tpm2tss -keyform engine -out key.csr -config csr.cnf
  expect "Enter password for user key:"
  send "\r\n"
  expect eof
EOF
```

**Comment by AndreasFuchsSIT** [comment]
the engine cannot know, if a password was set or not.
If the noda-flag is set, then the engine will attempt empty-auth before asking.
If the noda-flag is not set, then the engine will ask directly, because attempting empty-auth would increment your TPM's failure counter.

Thus, set the noda flag during key creation if that's your desire.

**Comment by dnoliver** [comment]
I updated my key to be created with the `noda` attribute and now it does not ask me for a password. 

Thank you for that information!
