### ISSUE TITLE
Honour $enginesdir from libcrypto.pc

### ISSUE THREAD

**Issue by dwmw2** [tpm2-software/tpm2-tss-engine#16]
OpenSSL puts the engine directory into its pkg-config file. Please use the result of `pkg-config --variable=enginesdir libcrypto` in preference to the hard-coded value.

**Comment by AndreasFuchsSIT** [comment]
@dwmw2 Do you know if there are any autotools makro's available or how other project to this ?
I've only seen PKG_CHECK_MODULES but no PKG_GET_VARIABLE or similar.
