### ISSUE TITLE
ownerauth value failed to be set via openssl.cnf

### ISSUE THREAD

**Issue by RaymWong** [tpm2-software/tpm2-tss-engine#163]
Hi,
The ownerauth value can not be passed in via the openssl.cnf file. See Test Sequence below.

Can the ownerauth and the parentauth values be passed in via the command line instead like ?
Writing these values statically is not desirable as it can be easily read out compare to taking in the password via command line input either via stdin.
Example:
echo "keypassword:ownerauth:parentauth" | openssl pkeyutl -engine tpm2tss -keyform engine -inkey rsa2.tss -decrypt -in mycipher -out mydata_decoded -passin stdin

1.) Test Sequence: Failed at decryption, ownerauth value is not set properly as ownerauth.size is zero.
tpm2_clear -c p
tpm2_changeauth -c owner owner123
tpm2tss-genkey -o owner123 -a rsa rsa2.tss
openssl rsa -engine tpm2tss -inform engine -in rsa2.tss -pubout -outform pem -out rsa2.pub
openssl pkeyutl -pubin -inkey rsa2.pub -in mydata -encrypt -out mycipher
OPENSSL_CONF=openssl.conf openssl pkeyutl -engine tpm2tss -keyform engine -inkey rsa2.tss -decrypt -in mycipher -out mydata_decoded

2.) Error Message
Creating primary key under owner.
WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:393:Esys_CreatePrimary_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x000009a2)
1995904496:error:80071097:tpm2-tss-engine:init_tpm_parent:Owner authorization failed:src/tpm2-tss-engine-common.c:505:
1995904496:error:80072096:tpm2-tss-engine:init_tpm_key:Authorization failed:src/tpm2-tss-engine-common.c:561:
1995904496:error:8007406F:tpm2-tss-engine:esys_ctx_free:Some unknown error occured:src/tpm2-tss-engine-common.c:106:
1995904496:error:8008C096:tpm2-tss-engine:rsa_priv_enc:Authorization failed:src/tpm2-tss-engine-rsa.c:160:
1995904496:error:8007406F:tpm2-tss-engine:esys_ctx_free:Some unknown error occured:src/tpm2-tss-engine-common.c:106:
1995904496:error:0D0DC006:asn1 encoding routines:ASN1_item_sign_ctx:EVP lib:../crypto/asn1/a_sign.c:208:

3.) openssl config file:
openssl_conf = openssl_init

[openssl_init]
engines = engine_section
[engine_section]
tpm2tss = tpm2tss_section
[tpm2tss_section]
engine_id = tpm2tss
dynamic_path = /usr/lib/arm-linux-gnueabihf/engines-1.1/libtpm2tss.so
default_algorithms = RSA,ECDSA
init = 1
#SET_TCTI = <TCTI_options>
SET_OWNERAUTH=owner123
#SET_PARENTAUTH =""

[req]
distinguished_name = subject

[subject]

**Comment by AndreasFuchsSIT** [comment]
Unfortunately, openssl does not have a way to pass multiple passwords into an engine, thus it must run via ENV or via openssl_conf.

I'll have a look at this...

**Comment by RaymWong** [comment]
Hi,
The issue is due to the dynamic path and the default_algorithms.
If the system already installed the engine, the dynamic_path has to be removed. If not it will cause engine name  collision. Also the "default_algorithms" seems to only support RSA. 

changing the config file to the follow will make it work
3.) openssl config file:
openssl_conf = openssl_init

[openssl_init]
engines = engine_section
[engine_section]
tpm2tss = tpm2tss_section
[tpm2tss_section]
engine_id = tpm2tss
#dynamic_path = /usr/lib/arm-linux-gnueabihf/engines-1.1/libtpm2tss.so
default_algorithms = RSA
init = 1
#SET_TCTI = <TCTI_options>
SET_OWNERAUTH=owner123
#SET_PARENTAUTH =""

[req]
distinguished_name = subject

[subject]

**Comment by AndreasFuchsSIT** [comment]
Great, mind to post a PR with updates to the config and maybe some inline-comments that explain things ?
