### ISSUE TITLE
Persistent keys support

### ISSUE THREAD

**Issue by rlillback** [tpm2-software/tpm2-tss-engine#164]
What is the current state of support for utilizing persistent keys inside of the TPM?
My application is to:
 1.) Create a persistent private key on the TPM in NVRAM (public on file system)
 2.) Use that persistent private key to create a CSR

Is this possible?  Issue/bug #24 states that persistent key support is a WIP for PR #14.  PR #14 references PR #33.  However, I can't find any usage documentation around this support?

Thanks!

**Comment by AndreasFuchsSIT** [comment]
Yes, it is possible. see https://github.com/tpm2-software/tpm2-tss-engine/blob/master/test/rsasign_persistent.sh

P.S. If you'd like, I'd appreciate any addition to the README here...
