### ISSUE TITLE
 Incompatibility with Strongswan due to the use of RSA decryption instead of RSA signature

### ISSUE THREAD

**Issue by lhuynh-cs** [tpm2-software/tpm2-tss-engine#171]
We are attempting to use a key hosted inside the TPM chip with Strongswan.
First we create a primary key:
$ tpm2_createprimary -C o -g sha256 -G rsa -c prim.ctx

Next we create a persistent child key:
$ tpm2_create -C prim.ctx -g sha256 -G rsa:rsassa -u key1.pub -r key1.priv
$ tpm2_load -C prim.ctx -u key1.pub -r key1.priv -c key1.ctx
$ tpm2_evictcontrol -C o -c key1.ctx 0x81000002

Using OpenSSL for CMP and the TPM TSS engine, we request a certificate for the TPM hosted child key:
$ openssl cmp -cmd ir -engine tpm2tss -server [PKI IP] -path [CMP alias path] -cert [client auth cert file] -key [client auth key file] -newkey engine:0x81000002 -subject "[DN]" -certout [enroled cert file] -srvcert [CMP server cert]

The above command fails as expected ("inconsistent attributes"),
because the engine uses the RSA decrypt operation,
but the "decrypt" attribute is not set on the key since its scheme is "rsassa":
    WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:305:Esys_RSA_Decrypt_Finish() Received TPM Error
    ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x00000182)
    139652227592192:error:8008C06D:tpm2-tss-engine:rsa_priv_enc:Unknown TPM error occured. Please check tpm2tss logs:src/tpm2-tss-engine-rsa.c:166:
    139652227592192:error:38064067:CRMF routines:CRMF_poposigningkey_init:error:crypto/crmf/crmf_lib.c:440:
    139652227592192:error:3907907B:CMP routines:OSSL_CMP_certreq_new:error creating ir:crypto/cmp/cmp_msg.c:338:

Now, we create the child key as a simple RSA key : tpm2_create -G rsa ...
The key has now the "decrypt" attribute set, and the enrollment request is OK,
but next in Strongswan, we get an error "no common hash algorithm found to create signature"
because the scheme attribute of the key is empty.

So, we try to replace the RSA decrypt by a RSA signature in tpm2-tss-engine-master/tpm2-engine-rsa.c, but face a memory corruption problem:
WARNING:marshal:src/tss2-mu/tpm2b-types.c:302:Tss2_MU_TPM2B_DIGEST_Marshal() buffer_size: 4096 with offset: 77 are insufficient for object of size XXXXX

where XXXXX is random at each execution of the "openssl cmp" command.

Thanks for help

**Comment by AndreasFuchsSIT** [comment]
Yes, the problem is that OpenSSL performs the padding operation (PSS or SSA) outside of the RSA-engines. Thus we only receive the raw data to be fed into the RSA operation.
The TPM however does not support "RAW-RSA" operations via the Sign() call.
Thus we need to use TPM's Decrypt() operation to perform the RAW-RSA operation, and thus we need the decrypt flag.

I know that this is counter-intuitive and a problem, but we had to deal with it and there was no other way, given the restrictions of the TPM and OpenSSL...

So please set the decrypt flag. Trying to get it to work via Sign will fail...

**Comment by AndreasFuchsSIT** [comment]
P.S. This was also explained in the README.md file:
https://github.com/tpm2-software/tpm2-tss-engine/blob/d79620378b681ecc2b6b63745e61a95ebc9b804e/README.md#key-types

**Comment by lhuynh-cs** [comment]
Hi,
Do you know if it is possible to sign with RSASSA and SHA256 using a TPM key which does not have the "scheme" and the "scheme-halg" attributes set ?

$ tpm2_readpublic -c  0x81000002
name: 000b6383...
qualified name: 000b06aa...
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|decrypt|sign
  raw: 0x60072
type:
  value: rsa
  raw: 0x1
exponent: 0x0
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: null
  raw: 0x10
sym-mode:
  value: (null)
  raw: 0x0
sym-keybits: 0
rsa: bce62535...

**Comment by bairathivivek** [comment]
I am also facing same issue. Please let me know how to resolve this issue for strongswan.

**Comment by AndreasFuchsSIT** [comment]
The encryption-scheme is handled by openssl. The engine does not change anything about it.
So get openssl to use ssa and you should be fine.

**Comment by bairathivivek** [comment]
Is there a way to do make openssl support SSA? I am not hands on with openssl code.

**Comment by AndreasFuchsSIT** [comment]
see rsa_padding_mode:mode here https://www.openssl.org/docs/man1.1.1/man1/openssl-pkeyutl.html

**Comment by bairathivivek** [comment]
Hi Andreas,

Thanks for reply.

Just wanted to confirm does this require changes in openssl code?

**Comment by AndreasFuchsSIT** [comment]
No, openssl supports this mode. You need to call openssl differently.
I don't know if you are using the commandline tool or the C-API of openssl.
