### ISSUE TITLE
Check if tpm is actually used with engine set in .cnf

### ISSUE THREAD

**Issue by nellorocca** [tpm2-software/tpm2-tss-engine#173]
Hi everyone,
I hope this was not covered in other issues, I havent's found anything related.

Basically I'd like to set tpm2tss as the default engine for openssl. I updated the .cnf file using the example and I'm trying to understand if the TPM is actually used by default.

What I can see is that the engine is correctly detected by openssl which lists it as "Available" if I launch `openssl engine -tt`.

Is there any way to get this information? Also, should I expect some operations to fallback by design to the MCU?

Thanks.

**Comment by AndreasFuchsSIT** [comment]
No clue. I guess you should probably ask upstream OpenSSL.

Note though that setting the engine as default is not enough. You still need to tell OpenSSL that the `keyform` is `engine`. And that is not possible via openssl.cnf unfortunately. A bit weird, but hey...
