### ISSUE TITLE
pandoc should not be a hard dependency

### ISSUE THREAD

**Issue by safayetahmedatge** [tpm2-software/tpm2-tss-engine#18]
pandoc is used to build the man pages. The configure script fails when pandoc is not installed.

https://github.com/tpm2-software/tpm2-tss-engine/blob/a7972896b674edc71e9cb50db8bdf8ce40e54686/configure.ac#L104

This should be a warning instead of an error. In tpm2-tools, the man pages are only built if pandoc is installed. The actual tools are built regardless.

https://github.com/tpm2-software/tpm2-tools/blob/8f14189cb5cefa4acbf949e9287e3ab074bdc750/configure.ac#L16

**Comment by AndreasFuchsSIT** [comment]
Sounds good and thanks a lot for the effort !
Merged...
