### ISSUE TITLE
Question: is there a way to test if a key handle (generated by tpm2tss-genkey) belongs to this TPM?

### ISSUE THREAD

**Issue by danielwangksu** [tpm2-software/tpm2-tss-engine#180]
I created a key handle using tpm2tss-genkey, is there a way (e.g. a command) to test if a key handle (generated by tpm2tss-genkey) belongs to a certain TPM? Thanks!

**Comment by AndreasFuchsSIT** [comment]
Unfortuantely not. If the TPM can load it, it belongs to the TPM, if not, then not.

**Comment by danielwangksu** [comment]
@AndreasFuchsSIT This is probably a stupid question. Do you mean use tpm2_load command? I'm not sure how to use tpm2_load with a key handle (e.g. key.tss) generated by tpm2tss-genkey

**Comment by AndreasFuchsSIT** [comment]
Sorry, no, loading is a part of using with the engine.
So this means you have to perform an operation with the key in order to know if it fits to the TPM.
