### ISSUE TITLE
OpenSSL 3.0 change from engines to providers

### ISSUE THREAD

**Issue by mpeylo** [tpm2-software/tpm2-tss-engine#186]
Hi,

I was wondering whether it was already detected in this context that upcoming OpenSSL 3.0 will introduce "[providers](https://www.openssl.org/docs/manmaster/man7/provider.html)" and deprecate "engines".

The current version of the [OpenSSL 3.0 wiki page](https://wiki.openssl.org/index.php/OpenSSL_3.0#Engines_and_.22METHOD.22_APIs) states

> Authors and maintainers of external engines are strongly encouraged to refactor their code transforming engines into providers using the new Provider API and avoiding deprecated methods.

Are there any plans regarding that already?

BR,
Martin

**Comment by AndreasFuchsSIT** [comment]
Acutally I did not see this
Good point... Someone should get startet. Got any time ?

**Comment by gotthardp** [comment]
Unless anyone else already started, I will try migrating to the OpenSSL 3.0 in the coming month(s). (Motivated by the hope that TPM-based restricted signing RSA keys will work there.)

**Comment by AndreasFuchsSIT** [comment]
I'd appreciate this effort.

**Comment by gotthardp** [comment]
@AndreasFuchsSIT, the good news is that with OpenSSL 3.0 and its new provider API one can generate keys using the standard `openssl genpkey`, can sign using restricted signing keys, and even use handles to persistent TPM keys, previously generated by tpm2-tools.
The drawback is that the structure of the code is very much different, so maintaining a common code for both the engine and the provider feels very hard as one would need yet another abstraction layer on top of the ESAPI.
I'd suggest to do a major refactoring of the existing code and adjust it to the new OpenSSL's structure. This way it remains simple and reviewable. I started something here: https://github.com/gotthardp/tpm2-openssl
Few basic features already work, but one needs the latest OpenSSL with my pending PR https://github.com/openssl/openssl/pull/13707

The idea is not to steal your work, but to prove a feasibility of the goal. validate the OpenSSL API and then (ideally) get the code integrated back as one of the tpm2 repos. Of course, after a larger review and discussion.

**Comment by AndreasFuchsSIT** [comment]
That is very good news indeed. Great to see this work progressing.

So given the constraint of having basically a rewrite of major parts but at the same time trying to get a good transition path in place for 3.0-provider support, how about the following:
We split the codebase here in this project into legacy-engine and new-provider code. A configure-flag (default:auto) can determine whether to build the engine or the provider.
Once <3.0 is deprecated in major distros, we can deprecate the legacy codebase here as well.

And if you'd like to keep some control; I've been searching for a 2nd maintainer for years now. Would be happy if you would like to take up that role.

**Comment by gotthardp** [comment]
Thanks. The engine API will continue to work even with OpenSSL 3.0, so the engine and the provider may even co-exist on one machine.
Considering the provider and the engine have almost nothing in common, not even tests nor documentation, I wonder whether it would be better to split the code into a new branch or a new project instead. This way both could keep the standard directory structure of man-src-tests.
The transition path would be to install OpenSSL 3 along with both the engine and the provider and then step-by step modify the apps until only the provider is used. This doesn't require a common repo, I believe. Or do you see other benefits of having a common project?

**Comment by AndreasFuchsSIT** [comment]
This is very much very awesome.
Would you like to move the project to the tpm2-software namespace (you could stay the maintainer) ?
Then you could also get a co-maintainer from the group for vacations and such.

**Comment by gotthardp** [comment]
Yes, if possible and acceptable for the group, I'd like to move there. Either now or any later point in time.

**Comment by AndreasFuchsSIT** [comment]
I added a note to the README pointing to tpm2-openssl
