### ISSUE TITLE
Link rpm engine to OpenSSL

### ISSUE THREAD

**Issue by paulduongemail** [tpm2-software/tpm2-tss-engine#190]
Hi,

I've already compile my tpm2-tss-engine to .dll

Next, how should I configure OpenSSL to add this engine? Should I just copy the configuration info from you provided from openssl.cnf.sample and overwrite the original openssl.cnf under C:\OpenSSL\SSL?

And one more question, in order to use command

```tpm2tss-genkey -a rsa -s 2048 myTPMPriKey.pem```

what should I do?

I'm trying to run this under Windows.

Thanks!

**Comment by AndreasFuchsSIT** [comment]
There should be no need to change the openssl.cnf file if you just want to use the engine without owner-pw.
Just add the -engine and -keyform parameters to the openssl commandline call.
