### ISSUE TITLE
Not able to use key from TPM due to signature algorithm missing in TPM key

### ISSUE THREAD

**Issue by bairathivivek** [tpm2-software/tpm2-tss-engine#199]
Hi,

**Commands ran to generate TPM keys:**
tpm2_createprimary -H o -g sha256 -G rsa -C context.out
tpm2_flushcontext --transient-object

tpm2_evictcontrol -A o -c context.out -S **0x81010001**
tpm2_flushcontext --transient-object

tpm2_create -H 0x81010001 -g sha256 -G rsa -u key2.pub -r key2.priv --object-attributes=sign\|decrypt\|fixedtpm\|fixedparent\|sensitivedataorigin\|userwithauth\|noda
tpm2_flushcontext --transient-object

tpm2_load -H 0x81010001 -u key2.pub -r key2.priv -C key2.ctx
tpm2_flushcontext --transient-object

tpm2_evictcontrol -A o -c key2.ctx -S **0x81010004**
tpm2_flushcontext --transient-object

[root@centos7 key]# tpm2_listpersistent
persistent-handle[0]:0x81010001 key-alg:rsa hash-alg:sha256 object-attr:fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
persistent-handle[1]:0x81010002 key-alg:rsa hash-alg:sha256 object-attr:fixedtpm|fixedparent|sensitivedataorigin|userwithauth|noda|decrypt|sign
persistent-handle[2]:0x81010003 key-alg:rsa hash-alg:sha256 object-attr:fixedtpm|fixedparent|sensitivedataorigin|userwithauth|noda|decrypt|sign
persistent-handle[3]:0x81010004 key-alg:rsa hash-alg:sha256 object-attr:fixedtpm|fixedparent|sensitivedataorigin|userwithauth|noda|decrypt|sign
[root@centos7 key]#

**Used above keys to generate cert using openssl cmp functionality.**
**Configured strongswan to use the above keys and cert, but getting following error:**

**Logs from strongswan while reading TPM key:**
Nov 24 12:02:42 centos7 charon: 00[CFG] loading secrets from '/etc/strongswan/ipsec.secrets'
Nov 24 12:02:42 centos7 charon: 00[CFG] no PKCS#11 module found having a keyid 81:01:00:04
Nov 24 12:02:42 centos7 charon: 00[PTS] TPM 2.0 via TSS2 v2 available
Nov 24 12:02:42 centos7 charon: 00[PTS] **signature algorithm is NULL with ERROR hash**
Nov 24 12:02:42 centos7 charon: 00[CFG]   **loaded private key from %smartcard:0x81010004**

**Logs from strongswan while bringing up tunnel:**
Nov 24 12:02:42 centos7 charon: 09[ENC] parsed IKE_SA_INIT response 0 [ SA KE No CERTREQ N(HASH_ALG) ]
Nov 24 12:02:42 centos7 charon: 09[CFG] selected proposal: IKE:AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_2048
Nov 24 12:02:42 centos7 charon: 09[IKE] received cert request for "C=gb, O=VF, OU=LAB, CN=VFPreProdRoot"
Nov 24 12:02:42 centos7 charon: 09[IKE] received cert request for "C=IN, ST=KA,L=BN, O=Mav, OU=System Test, CN=MavRootCaCert.com"
Nov 24 12:02:42 centos7 charon: 09[IKE] sending cert request for "C=IN, ST=KA, L=BN, O=Mav, OU=System Test, CN=MavRootCaCert.com"
Nov 24 12:02:42 centos7 charon: 09[IKE] sending cert request for "C=GB, O=VF, OU=Lab, CN=VFPreProdIssuingCA1"
Nov 24 12:02:42 centos7 charon: 09[IKE] sending cert request for "C=gb, O=VF, OU=LAB, CN=VFPreProdRoot"
Nov 24 12:02:42 centos7 charon: 09[IKE] **no common hash algorithm found to create signature with RSA key**

**I have one more setup and there I didn't face the above issue. Here's the log of strongswan:**

**Logs from strongswan while reading TPM key:**
Nov 24 14:39:55 centos7 charon: 00[CFG] loading secrets from '/etc/strongswan/ipsec.secrets'
Nov 24 14:39:55 centos7 charon: 00[CFG] no PKCS#11 module found having a keyid 81:01:00:04
Nov 24 14:39:55 centos7 charon: 00[PTS] TPM 2.0 via TSS2 v2 available
Nov 24 14:39:55 centos7 charon: 00[PTS] **signature algorithm is NULL with ERROR hash**
Nov 24 14:39:55 centos7 charon: 00[CFG]   **loaded private key from %smartcard:0x81010004**

**Logs from strongswan while bringing up tunnel:**
Nov 24 14:39:56 centos7 charon: 08[ENC] parsed IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) CERTREQ N(FRAG_SUP) ]
Nov 24 14:39:56 centos7 charon: 08[CFG] selected proposal: IKE:AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_2048
Nov 24 14:39:56 centos7 charon: 08[IKE] received cert request for "CN=VC CA, C=GB"
Nov 24 14:39:56 centos7 charon: 08[IKE] received 1 cert requests for an unknown ca
Nov 24 14:39:56 centos7 charon: 08[IKE] sending cert request for "CN=VC CA, C=GB"
Nov 24 14:39:56 centos7 charon: 08[IKE] sending cert request for "C=IN, ST=KA, L=BN, O=Mav, OU=System Test, CN=MavRootCaCert.com"
Nov 24 14:39:56 centos7 charon: 08[IKE] **authentication of 'CN=9017049559, O=VC, C=GB' (myself) with RSA signature successful**
Nov 24 14:39:56 centos7 charon: 08[IKE] sending end entity cert "CN=9017049559, O=VC, C=GB"
Nov 24 14:39:56 centos7 charon: 08[IKE] establishing CHILD_SA du_ipsec{1}
Nov 24 14:39:56 centos7 charon: 08[ENC] generating IKE_AUTH request 1 [ IDi CERT CERTREQ AUTH SA TSi TSr N(MOBIKE_SUP) N(ADD_4_ADD
R) N(ADD_4_ADDR) N(EAP_ONLY) N(MSG_ID_SYN_SUP) ]
Nov 24 14:39:56 centos7 charon: 08[ENC] splitting IKE message (1456 bytes) into 2 fragments
Nov 24 14:39:56 centos7 charon: 08[ENC] generating IKE_AUTH request 1 [ EF(1/2) ]
Nov 24 14:39:56 centos7 charon: 08[ENC] generating IKE_AUTH request 1 [ EF(2/2) ]
Nov 24 14:39:56 centos7 charon: 08[NET] sending packet: from 172.17.10.2[4500] to 172.16.100.21[4500] (1236 bytes)
Nov 24 14:39:56 centos7 charon: 08[NET] sending packet: from 172.17.10.2[4500] to 172.16.100.21[4500] (292 bytes)
Nov 24 14:39:56 centos7 charon: 10[NET] received packet: from 172.16.100.21[4500] to 172.17.10.2[4500] (1124 bytes)
Nov 24 14:39:56 centos7 charon: 10[ENC] parsed IKE_AUTH response 1 [ EF(1/3) ]
Nov 24 14:39:56 centos7 charon: 10[ENC] received fragment #1 of 3, waiting for complete IKE message
Nov 24 14:39:56 centos7 charon: 11[NET] received packet: from 172.16.100.21[4500] to 172.17.10.2[4500] (1124 bytes)
Nov 24 14:39:56 centos7 charon: 11[NET] received packet: from 172.16.100.21[4500] to 172.17.10.2[4500] (1124 bytes)
Nov 24 14:39:56 centos7 charon: 11[ENC] parsed IKE_AUTH response 1 [ EF(2/3) ]
Nov 24 14:39:56 centos7 charon: 11[ENC] received fragment #2 of 3, waiting for complete IKE message
Nov 24 14:39:56 centos7 charon: 12[NET] received packet: from 172.16.100.21[4500] to 172.17.10.2[4500] (116 bytes)
Nov 24 14:39:56 centos7 charon: 12[ENC] parsed IKE_AUTH response 1 [ EF(3/3) ]
Nov 24 14:39:56 centos7 charon: 12[ENC] received fragment #3 of 3, reassembled fragmented IKE message (2208 bytes)
Nov 24 14:39:56 centos7 charon: 12[ENC] parsed IKE_AUTH response 1 [ IDr CERT CERT AUTH N(MSG_ID_SYN_SUP) SA TSi TSr ]
Nov 24 14:39:56 centos7 charon: 12[IKE] received end entity cert "CN=FG6H1ETB20901837, O=VC, C=GB"
Nov 24 14:39:56 centos7 charon: 12[IKE] received issuer cert "CN=VC CA, C=GB"
Nov 24 14:39:56 centos7 charon: 12[CFG]   using certificate "CN=FG6H1ETB20901837, O=VC, C=GB"
Nov 24 14:39:56 centos7 charon: 12[CFG]   using trusted ca certificate "CN=VC CA, C=GB"
Nov 24 14:39:56 centos7 charon: 12[CFG] checking certificate status of "CN=FG6H1ETB20901837, O=VC, C=GB"
Nov 24 14:39:56 centos7 charon: 12[CFG] certificate status is not available
Nov 24 14:39:56 centos7 charon: 12[CFG]   reached self-signed root ca with a path length of 0
Nov 24 14:39:56 centos7 charon: 12[IKE] **authentication of 'CN=FG6H1ETB20901837, O=VC, C=GB' with RSA signature successful**
Nov 24 14:39:56 centos7 charon: 12[IKE] IKE_SA du_ipsec[1] established between 172.17.10.2[CN=9017049559, O=VC, C=GB]...172.1
6.100.21[CN=FG6H1ETB20901837, O=VC, C=GB]
Nov 24 14:39:56 centos7 charon: 12[IKE] scheduling rekeying in 80674s
Nov 24 14:39:56 centos7 charon: 12[IKE] maximum IKE_SA lifetime 84274s
Nov 24 14:39:56 centos7 charon: 12[CFG] selected proposal: ESP:AES_CBC_256/HMAC_SHA2_256_128/NO_EXT_SEQ
Nov 24 14:39:56 centos7 kernel: alg: No test for fips(ansi_cprng) (fips_ansi_cprng)
Nov 24 14:39:56 centos7 charon: 12[IKE] **CHILD_SA du_ipsec{1} established with SPIs c61449c7_i 75846b5d_o and TS 172.17.11.2/32 === 10.0.1.0/24 10.0.9.0/24**

**The only difference I found between the 2 setups is that one which is not working has a ROOT CA of Modulus key length 4096 bit and the other working one has root CA of Modulus 2048 bit. Could that be the issue ?**

**Please let me know what could be the issue here and how we can resolve it.**

**TPM software versions used:**
tpm2-tss-engine-1.0.1.tar.gz
tpm2-abrmd-2.0.0-1.el7.x86_64
tpm2-tss-2.3.1-1.el7.x86_64
tpm2-tools-3.2.0-1.el7.x86_64

[root@centos7 key]# /opt/mavenir/mnxt/bin/openssl version
OpenSSL 3.0.0-dev xx XXX xxxx
[root@centos7 key]#

Waiting for your reply.

Thanks & Regards,
Vivek

**Comment by AndreasFuchsSIT** [comment]
Is the tpm2-tss-engine even used in this setup in the error path ?
If I understand this ocrrectly, it's used only for the CSR generation ?
If it has to do with rootca cert verification, then this is something where strongswan has the bug ?

**Comment by bairathivivek** [comment]
Hi Andreas ,

Thanks for the reply.

I just found out that the setup in which the tunnel is not coming up is due to the support of IKEv2 signature authentication extension (RFC 7427, i.e. HASH_ALG notify).

When strongswan gets HASH_ALG notification payload it checks the signature algorithm associated with the TPM key and if it finds none it throws error. This is visible from below logs:

**Logs from strongswan while reading TPM key:**
Nov 24 14:39:55 centos7 charon: 00[CFG] loading secrets from '/etc/strongswan/ipsec.secrets'
Nov 24 14:39:55 centos7 charon: 00[CFG] no PKCS#11 module found having a keyid 81:01:00:04
Nov 24 14:39:55 centos7 charon: 00[PTS] TPM 2.0 via TSS2 v2 available
Nov 24 14:39:55 centos7 charon: 00[PTS] **signature algorithm is NULL with ERROR hash**
Nov 24 14:39:55 centos7 charon: 00[CFG] loaded private key from %smartcard:0x81010004

Logs from strongswan while bringing up tunnel:
Nov 24 12:02:42 centos7 charon: 09[ENC] parsed IKE_SA_INIT response 0 [ SA KE No CERTREQ **N(HASH_ALG) ]**
Nov 24 12:02:42 centos7 charon: 09[CFG] selected proposal: IKE:AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_2048
Nov 24 12:02:42 centos7 charon: 09[IKE] received cert request for "C=gb, O=VF, OU=LAB, CN=VFPreProdRoot"
Nov 24 12:02:42 centos7 charon: 09[IKE] received cert request for "C=IN, ST=KA,L=BN, O=Mav, OU=System Test, CN=MavRootCaCert.com"
Nov 24 12:02:42 centos7 charon: 09[IKE] sending cert request for "C=IN, ST=KA, L=BN, O=Mav, OU=System Test, CN=MavRootCaCert.com"
Nov 24 12:02:42 centos7 charon: 09[IKE] sending cert request for "C=GB, O=VF, OU=Lab, CN=VFPreProdIssuingCA1"
Nov 24 12:02:42 centos7 charon: 09[IKE] sending cert request for "C=gb, O=VF, OU=LAB, CN=VFPreProdRoot"
Nov 24 12:02:42 centos7 charon: 09[IKE] **no common hash algorithm found to create signature with RSA key**

**Is there any command/way to set signature algorithm like RSASSA in the created TPM keys?**

Following are the signature schemes supported by TPM2.0:
RSASSA
RSAPSS
ECDSA

Thanks & Regards,
Vivek

**Comment by AndreasFuchsSIT** [comment]
How do you call openssl to perform the signature operation ?
Please post you code or cli calls.

If you are doing it all correctly, then "RSASSA-PKCS1-v1_5 as specified in RFC 3447" should be used by default.

**Comment by bairathivivek** [comment]
**Openssl commands to generate certificates using CMP:**

openssl cmp -engine tpm2tss -config /data/storage/.secure/.cmp/cmp.cnf -section ir

[root@centos7 key]# cat /data/storage/.secure/.cmp/cmp.cnf
[default]

#CA certficate dir
cacertdir = /data/storage/.secure/.cmp/ipsec.d/cacerts
#certficate dir
certdir = /data/storage/.secure/.cmp/ipsec.d/certs

#server info
server = 10.1.26.116:449

#server path
path = cmp

#client subject name
subject = "/C=IN/O=mav/OU=qa/CN=ITIPSECTPM"

#client trusted operator root ca certificate
trusted = $cacertdir/MavRootCaCert.pem,$cacertdir/OperatorCA.pem,$cacertdir/cmpca.pem,$cacertdir/mavCA1Cert.pem

#CMS/CA CN name
recipient = "/C=IN/O=mav/OU=qa/CN=cmpca"

#client certifcate
certout = $certdir/client.pem

#CMS/intermediate operator CA certificate
cacertsout = $cacertdir/OperatorCA.pem

# default cmp request
cmd = ir

unprotectederrors = 1

ignore_keyusage = 1


#cmp section
[cmp]


#initization request
[ir]

# ir request
cmd = ir

#vendor certifcate
cert = $default::certdir/vendor.pem

#vendor key
key = engine:0x81010003
keypass = pass:+vcT2eFEE9WggNgfrAwPojp/9NE=

#client new certificate
certout = $default::certout

#client new key
newkey = engine:0x81010004
newkeypass = pass:+vcT2eFEE9WggNgfrAwPojp/9NE=


#certificate renewal section
[cr]

# cr request
cmd = cr

#client old certifcate
cert = $default::certout

#client old key
key = engine:0x81010004
keypass = pass:+vcT2eFEE9WggNgfrAwPojp/9NE=

#client new key
newkey = engine:0x81010004
newkeypass = pass:+vcT2eFEE9WggNgfrAwPojp/9NE=

#client new certificate
certout = $default::certout


#key update or certificate renewal section
[kur]

# KUR request
cmd = kur

#client old certifcate
cert = $default::certout

#client old key
key = engine:0x81010004
keypass = pass:+vcT2eFEE9WggNgfrAwPojp/9NE=

#client new key
newkey = engine:0x81010005
newkeypass = pass:+vcT2eFEE9WggNgfrAwPojp/9NE=

#client new certificate
certout = $default::certdir/client_newcert.pem

#client intermediate CA certificate
#extracerts = $default::cacertsout
[root@centos7 key]#

[root@centos7 key]# cat ipsec.secrets
# ipsec.secrets - strongSwan IPsec secrets file

: PIN %smartcard:0x81010004 +vcT2eFEE9WggNgfrAwPojp/9NE=
[root@centos7 key]#

Thanks & Regards,
Vivek

**Comment by bairathivivek** [comment]
**Forgot to add code link:
Don't know the exact line of code but here's the code link for openssl cmp code:
https://github.com/mpeylo/cmpossl/tree/cmp/crypto/cmp**

Let me know if you need anything else.

Thanks.

**Comment by AndreasFuchsSIT** [comment]
I'm sorry, but I don't even see where the calls to the engine are made. Just too much code unrelated to this project.

**Comment by AndreasFuchsSIT** [comment]
I think I cannot help you at this point, until you're deeper in the call chain where the tpm2-tss engine is called as well.
Maybe one more tip: try `./configure --enable-debug=yes` to get more info from the engine.
Or try `export TSS2_LOG=esys+trace` to get more info from the tss.

**Comment by bairathivivek** [comment]
Hi Andreas,

Thanks for the reply.

You are right the issue is not with the tpm2-tss-engine but looks like its with the version of tpm I am using. It doesn't have an option to set signature schemes like RSASSA.
And because scheme is not set during the generation of TPM key, strongswan when reads that key could not able to find out the scheme and instead of defaulting to "RSASSA-PKCS1-v1_5 as specified in RFC 3447" it gives an error. Not sure if this can be called an issue in strongswan.

So, I think I need to upgrade the tpm2-tss library or tpm2_tools to generate a TPM key with signature scheme.

Having said that I saw one more issue reported here - **https://github.com/tpm2-software/tpm2-tss-engine/issues/171** - which states that if we set signature scheme in TPM key, openssl returns error as 'decrypt' attribute will not be set.
So, it will become a chicken and egg situation. If i use RSASSA scheme while generating TPM key, openssl has issue but if I don't use RSASSA scheme, strongswan has issue.

Can openssl error be resolved by running following command. Here I am setting rsassa scheme and attribute as sign and decrypt both.
**tpm2_create -H 0x81010001 -K Ph03nix5parr0w! -g sha256 -G rsa -u key2.pub -r key2.priv --object-attributes=**sign|decrypt**|fixedtpm|fixedparent|sensitivedataorigin|userwithauth|noda**

Will the above command work? If yes, then wiil it resolve issue for both openssl and strongswan?

Waiting for your comments.


Thanks & Regards,
Vivek

**Comment by gotthardp** [comment]
I believe this problem cannot be solved:
* TCG TPM specification says the combined (signing and decryption) keys shall not be restricted and shall use the NULL signature scheme.
* strongSwan reads the key scheme and hash algorithm from the key information, i.e. expects the signature scheme and hash to be non-NULL.

You can create a restricted signing key with the tpm2 tools and use that with strongswan, but such key cannot be used for signing with the tpm2-tss-engine, because it does not support signing using a restricted signing key, due to an opessl API limitation.

**Comment by bairathivivek** [comment]
Thanks @gotthardp for the reply.
