### ISSUE TITLE
"authorization failure without DA implications"  when creating a CSR

### ISSUE THREAD

**Issue by tannoa2** [tpm2-software/tpm2-tss-engine#208]
I am getting an authentication failure when trying to create a CSR using the tpm2tss engine. 
Any help would appreciated 
Here are my steps:
**root@9274091a3c6d:~/certs# tpm2tss-genkey -p lab1 -o lab1 -a ecdsa -v -s 256 pri_pub_blob.key**
Engine name: TPM2-TSS engine for OpenSSL
Init result: 1
Generating the ecdsa key
Writing key to disk
*** SUCCESS ***

**root@9274091a3c6d:~/certs# openssl req -new  -engine tpm2tss -keyform engine -key** pri_pub_blob.key -out client.csr
engine "tpm2tss" set.
Enter password for user key:
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value
Country Name (2 letter code) [AU]:
State or Province Name (full name) [Some-State]:
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:
Email Address []:

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:
WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:400:Esys_CreatePrimary_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x000009a2)
140121955333440:error:80071097:tpm2-tss-engine:init_tpm_parent:Owner authorization failed:src/tpm2-tss-engine-common.c:508:
140121955333440:error:80072096:tpm2-tss-engine:init_tpm_key:Authorization failed:src/tpm2-tss-engine-common.c:564:
140121955333440:error:8007406F:tpm2-tss-engine:esys_ctx_free:Some unknown error occured:src/tpm2-tss-engine-common.c:106:
140121955333440:error:80078096:tpm2-tss-engine:ecdsa_sign:Authorization failed:src/tpm2-tss-engine-ecc.c:220:
140121955333440:error:8007406F:tpm2-tss-engine:esys_ctx_free:Some unknown error occured:src/tpm2-tss-engine-common.c:106:
140121955333440:error:0D0DC006:asn1 encoding routines:ASN1_item_sign_ctx:EVP lib:../crypto/asn1/a_sign.c:224:

**root@9274091a3c6d:~/certs# tpm2_rc_decode  0x000009a2**
tpm:session(1):authorization failure without DA implications

**root@9274091a3c6d:~/certs# tpm2_getcap properties-variable**
TPM2_PT_PERSISTENT:
  ownerAuthSet:              1
  endorsementAuthSet:        1
  lockoutAuthSet:            1
  reserved1:                 0
  disableClear:              0
  inLockout:                 0
  tpmGeneratedEPS:           1
  reserved2:                 0
TPM2_PT_STARTUP_CLEAR:
  phEnable:                  1
  shEnable:                  1
  ehEnable:                  1
  phEnableNV:                1
  reserved1:                 0
  orderly:                   1
TPM2_PT_HR_NV_INDEX: 0x8
TPM2_PT_HR_LOADED: 0x0
TPM2_PT_HR_LOADED_AVAIL: 0x3
TPM2_PT_HR_ACTIVE: 0x0
TPM2_PT_HR_ACTIVE_AVAIL: 0x40
TPM2_PT_HR_TRANSIENT_AVAIL: 0x3
TPM2_PT_HR_PERSISTENT: 0x1
TPM2_PT_HR_PERSISTENT_AVAIL: 0x12
TPM2_PT_NV_COUNTERS: 0x0
TPM2_PT_NV_COUNTERS_AVAIL: 0x10
TPM2_PT_ALGORITHM_SET: 0x1
TPM2_PT_LOADED_CURVES: 0x2
TPM2_PT_LOCKOUT_COUNTER: 0x0
TPM2_PT_MAX_AUTH_FAIL: 0xA
TPM2_PT_LOCKOUT_INTERVAL: 0x1C20
TPM2_PT_LOCKOUT_RECOVERY: 0x15180
TPM2_PT_NV_WRITE_RECOVERY: 0x0
TPM2_PT_AUDIT_COUNTER_0: 0x0
TPM2_PT_AUDIT_COUNTER_1: 0x0

**Comment by AndreasFuchsSIT** [comment]
You need to set the owner authorization using the environment variable for this to work.
