### ISSUE TITLE
Missing `getopt`

### ISSUE THREAD

**Issue by safayetahmedatge** [tpm2-software/tpm2-tss-engine#210]
### Issue
Trying to build tpm2-tss-engine, an error was reported about missing `optind` and `optarg`.

### Details
I've seen references such as the following that suggest "std=c99 ...  prevents the POSIX macros from being defined in <features.h>".
https://stackoverflow.com/questions/22575940/getopt-not-included-implicit-declaration-of-function-getopt/22576057

If I configure the source with `--disable-defaultflags` and manually set all the compiler flags through `CFLAGS` environment variable, I no longer get the above-mentioned error.

### Proposed solution
Consider removing the following line.
https://github.com/tpm2-software/tpm2-tss-engine/blob/6425b6fa29780d5fc5b6f874256eee610a409c71/configure.ac#L87

**Comment by williamcroberts** [comment]
I see tpm2tss-keygen pulls in getopt.h and not unistd.h which defines the actual vars. What if you `#include <unistd.h>` does that fix it?

```diff
diff --git a/src/tpm2tss-genkey.c b/src/tpm2tss-genkey.c
index 2e2c2e546436..9b9423f9b82a 100644
--- a/src/tpm2tss-genkey.c
+++ b/src/tpm2tss-genkey.c
@@ -32,6 +32,7 @@
 #include <string.h>
 #include <strings.h>
 #include <inttypes.h>
+#include <unistd.h>
 #include <getopt.h>
 
 #include <openssl/conf.h>
```

**Comment by safayetahmedatge** [comment]
@williamcroberts I tried including `unistd.h`. The build threw the same error, still.

**Comment by williamcroberts** [comment]
> @williamcroberts I tried including `unistd.h`. The build threw the same error, still.

Interesting, can you do one more thing for me, can you add gnu99?
```diff
diff --git a/configure.ac b/configure.ac
index d250a2ecf173..f7d8715a9ed7 100644
--- a/configure.ac
+++ b/configure.ac
@@ -84,7 +84,7 @@ AC_ARG_ENABLE([defaultflags],
               [enable_defaultflags=yes])
 AS_IF([test "x$enable_defaultflags" = "xyes"],
       [
-      AX_ADD_COMPILER_FLAG([-std=c99])
+      AX_ADD_COMPILER_FLAG([-std=gnu99])
       AX_ADD_COMPILER_FLAG([-Wall])
       AX_ADD_COMPILER_FLAG([-Wextra])
       AX_ADD_COMPILER_FLAG([-Wformat-security])
```

I cant repro your warning, so if you could also give me insight to your environment that would be great. This way I don't have to keep bugging you :-p

**Comment by safayetahmedatge** [comment]
Not at all bugging. Your help is much appreciated!

I added the `-std=gnu99` flag as you listed above. Unfortunately, I still get the same error.

I'm building for QNX 7.1. The QNX SDP provides a gcc cross compiler. It reports `(GCC) 8.3.0 `.

I'm not a 100% sure. I could be mistaken, but I believe it's using glibc, or some derivative.

**Comment by safayetahmedatge** [comment]
@williamcroberts 

I would like to correct my previous comment. I misread the change you suggested: originally, I added "-std=gnu99", but did not remove "-std=c99".

After I removed "-std=c99", I no longer get an error about missing "optarg" or "optind".

Thank you!

**Comment by williamcroberts** [comment]
@safayetahmedatge could you share the diff or submit a PR? Just so we can clearly identify the fix.

**Comment by safayetahmedatge** [comment]
@williamcroberts  I'm still not able to submit a PR yet. (I apologize if this is inconvenient)

The changes were exactly what you indicated above:
```
diff --git a/configure.ac b/configure.ac
index dae7d68..8c6f0ea 100644
--- a/configure.ac
+++ b/configure.ac
@@ -84,7 +84,7 @@ AC_ARG_ENABLE([defaultflags],
               [enable_defaultflags=yes])
 AS_IF([test "x$enable_defaultflags" = "xyes"],
       [
-      AX_ADD_COMPILER_FLAG([-std=c99])
+      AX_ADD_COMPILER_FLAG([-std=gnu99])
       AX_ADD_COMPILER_FLAG([-Wall])
       AX_ADD_COMPILER_FLAG([-Wextra])
       AX_ADD_COMPILER_FLAG([-Wformat-security])
```
As well as the additional minor change noted here:
https://github.com/tpm2-software/tpm2-tss-engine/issues/211#issue-866453588

thanks
