### ISSUE TITLE
Explicit `libdl` linking may no longer be needed

### ISSUE THREAD

**Issue by safayetahmedatge** [tpm2-software/tpm2-tss-engine#211]
The current approach to linking against `libdl` is not portable to QNX
https://github.com/tpm2-software/tpm2-tss-engine/blob/6425b6fa29780d5fc5b6f874256eee610a409c71/Makefile.am#L40

I think this should be handled as a part of `TSS2_TCTILDR_LIBS` in:
https://github.com/tpm2-software/tpm2-tss-engine/blob/6425b6fa29780d5fc5b6f874256eee610a409c71/Makefile.am#L39

Consider removing `-ldl` or replacing with `$(LIBADD_DL)` as in:
https://github.com/tpm2-software/tpm2-tss/blob/c6b77ca306dc35c88aeceaeb6ade37460d1e6dbc/Makefile.am#L278

**Comment by williamcroberts** [comment]
@safayetahmedatge looks like it can just be deleted, its unused.
