### ISSUE TITLE
Any recommendation for good code base that use tpm2tss engine?

### ISSUE THREAD

**Issue by danielwangksu** [tpm2-software/tpm2-tss-engine#227]
Is there any good code base for reference when implementing TLS, encryption/decryption using tpm2tss openSSL engine? I could not find good document/example that uses the engine. I figured out how to use the keys in TPM in a basic scenario but not exactly sure if I'm doing is correct or not. It would be great if someone who are experienced can point out a good reference project. Thanks!

**Comment by AndreasFuchsSIT** [comment]
How about nginx or curl ?
Just set the engine there and you're fine...
See https://www.youtube.com/watch?v=NFQ22SBlejk
