### ISSUE TITLE
How to generate key pair and csr using tss engine

### ISSUE THREAD

**Issue by ma3goul** [tpm2-software/tpm2-tss-engine#228]
Hi All ,

I want to generate a key pair and a csr using the tss engine .
What is the command for that please .

Thank you

**Comment by aaronUniontech** [comment]
openssl req -utf8 -engine tpm2tss -keyform engine -new -key rsa.tss -out myrequest.csr -subj "/C=CN/ST=Hubei/L=Wuhan/O=UniontechCompany/CN=zhangya@uniontech.com"

**Comment by aaronUniontech** [comment]
> openssl req -utf8 -engine tpm2tss -keyform engine -new -key rsa.tss -out myrequest.csr -subj "/C=CN/ST=Hubei/L=Wuhan/O=UniontechCompany/CN=[zhangya@uniontech.com](mailto:zhangya@uniontech.com)"

but it's not using tpm.so, now, tpm engine does not support generate csr.
