### ISSUE TITLE
self-signed certificate using openssl TPM2.0 engine

### ISSUE THREAD

**Issue by sachingole** [tpm2-software/tpm2-tss-engine#24]
following are steps to generate self signed certificate using openssl :-
1. RSA private key generation
openssl req -config csr.conf -nodes -new -newkey rsa:2048 -out server.csr
2. self signed certificate 
openssl req -x509 -sha256 -days 365 -key server.key -in server.csr -out server.pem

Similarly trying to generate self signed certificate using openssl TPM2.0 engine :-

Following steps are executed :-

1. TPM support is enabled on Raspberry Pi image as per below steps.
https://letstrust.de/archives/9-Howto-Enable-TPM-Support-on-a-Raspberry-PI-0,-0W,-1,-2,-3-and-make-it-work-with-the-LetsTrust-TPM.html

2. Linux TPM2 and TSS2 Software installed from below link
https://github.com/tpm2-software
tpm2-tss-engine
tpm2-tss
tpm2-tools
https://github.com/tpm2-software/tpm2-tss-engine

3. Generate key pair using TPM2.0 
root@raspberrypi:/home/pi# tpm2_createprimary -g sha256 -G ecc -o context.out
root@raspberrypi:/home/pi# tpm2_create -C 0x80000002 -G ecc256 -u k.pub -r k.priv

Question :-
1. Generated public and private key is encrypted, how to decrypt ? Is this right command to generate key pair ?
2. How to creates CSR (Certificate Signing Request) using openssl tpm 2.0 engine ?
3. How to generated self signed certificate using openssl tpm 2.0 engine ?

**Comment by AndreasFuchsSIT** [comment]
3. use tpm2tss-genkey to generate the key, not tpm2_create !

1. Private key is encrypted and will remain encrypted, because only the TPM can use it.
you can retrieve the public key though, see README.md

2. Should be as easy as adding -engine tpm2tss -inform engine to the csr call

3. Same as 2.

Tell me if it works for you.

**Comment by sachingole** [comment]
Thanks for quick help.

tpm2tss-genkey used after tpm2_createprimary 

root@raspberrypi:/home/pi/test_key# tpm2tss-genkey -a ecdsa -v -s 256 context.out 
Initializing
Engine name: TPM2-TSS engine for OpenSSL
Init result: 1 
Setting owner auth to empty auth.
Generating the key
GenKey for ecdsa.
Establishing connection with TPM.
WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-default.so 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-tabrmd.so 
Creating primary key under owner.
WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:416:Esys_CreatePrimary_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:156:Esys_CreatePrimary() Esys Finish ErrorCode (0x00000902) 
WARNING:esys:src/tss2-esys/esys_context.c:117:Esys_Finalize() Finalizing NULL context. 
Error: Generating key failed
Key could not be generated.
root@raspberrypi:/home/pi/test_key# 

any help on this.

**Comment by AndreasFuchsSIT** [comment]
Error 0x902 means that the three keyslots of your TPM RAM are full. The tpm2tss engine requires two keyslots for operations.

I assume that you played around with some of your things before and/or did not use a resource manager.
If you don't know what the issue was, try rebooting, that empties the TPMs RAM.

**Comment by AndreasFuchsSIT** [comment]
P.S. you can use the command `tpm2_rc_decode 0x00000902` to decode error codes.

**Comment by sachingole** [comment]
Thanks, tpm2_rc_decode is useful.

root@raspberrypi:/home/pi/test_key# tpm2tss-genkey -a ecdsa -v -s 256 context.out 
Initializing
Engine name: TPM2-TSS engine for OpenSSL
Init result: 1 
Setting owner auth to empty auth.
Generating the key
GenKey for ecdsa.
Establishing connection with TPM.
WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-default.so 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-tabrmd.so 
Creating primary key under owner.
Generating the ECC key inside the TPM.
Generated the ECC key inside the TPM.
Writing key to disk
*** SUCCESS ***
root@raspberrypi:/home/pi/test_key# 

csr request tried with below command. It stuck 
root@raspberrypi:/home/pi/test_key# openssl req -config csr.conf -engine tpm2tss -inform pem -out server.csr
Initializing
engine "tpm2tss" set.

How to pass key handle to this command or context.out which is received on tpm2_createprimary

**Comment by AndreasFuchsSIT** [comment]
Not supported yet. PR #14 is working on support for using TPM-persistent keys (stored inside the TPM using evictcontrol).

context.out files will not be supported directly. One could think of extending genkey to also consume context.out, and convert them to the PEM-file format.
If you want to work on this, please feal free.

Glad it's working for you, so I guess we can close this bug now ?
If you want, please add some information about this to the README or manpage of this project, so others can learn from you.

**Comment by matthias1000** [comment]
@sachingole 

The output of tpm2tss-genkey is not a "context", i.e. not what tpm_create would generate. Instead it is a PEM file that you can pass to openssl.

To create a csr for the key you created with tpm2tss-genkey:

`openssl req -new -engine tpm2tss -keyform engine -out server.csr -key $NAME_OF_YOUR_GENKEY_OUTPUT`

**Comment by sachingole** [comment]
@AndreasFuchsSIT and @matthias1000  Thank you. I am able to get self signed certificate with below commands.

# tpm2tss-genkey -a ecdsa -v -s 256 pri_pub_blob.key
# openssl req -new -x509 -engine tpm2tss -keyform engine -key pri_pub_blob.key -out client.crt

**Comment by AndreasFuchsSIT** [comment]
@sachingole If you don't mind, a PR to extend the README.md or even the man-page is allways appreciated.

**Comment by sachingole** [comment]
@AndreasFuchsSIT 
I have tried to commit branch but it gives following error.

I am attaching updated README.md file for your reference.
[README.zip](https://github.com/tpm2-software/tpm2-tss-engine/files/2482796/README.zip)


sachin@sachin-VirtualBox:~/work/tpm2$ git push --set-upstream origin self-signed-cert
Username for 'https://github.com': sachingole
Password for 'https://sachingole@github.com': 
remote: Permission to tpm2-software/tpm2-tss-engine.git denied to sachingole.
fatal: unable to access 'https://github.com/tpm2-software/tpm2-tss-engine/': The requested URL returned error: 403
sachin@sachin-VirtualBox:~/work/tpm2$

**Comment by AndreasFuchsSIT** [comment]
@sachingole Yes, you have to fork this project to your personal namespace, push to the new repository there (including a "signed-off-by" tag and then click on "pull request" in the web-gui.
But this is ok for the moment as well.

**Comment by sachingole** [comment]
@AndreasFuchsSIT  https://github.com/tpm2-software/tpm2-tss-engine/pull/32 "pull request" is generated.

**Comment by AndreasFuchsSIT** [comment]
Handled via #32 
Thanks !
