### ISSUE TITLE
tpm2-tss-engine:func(151):The provided digest value is too large:src/tpm2-tss-engine-digest-sign.c:115:

### ISSUE THREAD

**Issue by CIPop** [tpm2-software/tpm2-tss-engine#248]
With latest code from master, we're observing a failure in the TPM2 TSS engine:

`sudo openssl s_client -connect <hidden>.azure-devices.net:8883 -cert my_cert.pem -key my_tpm_key.tss -keyform engine -engine tpm2tss`

```
<... connects>
140028234097984:error:8009706E:tpm2-tss-engine:func(151):The provided digest value is too large:src/tpm2-tss-engine-digest-sign.c:115:
140028234097984:error:141F0006:SSL routines:tls_construct_cert_verify:EVP lib:../ssl/statem/statem_lib.c:308:
<connection closed>
```

The same call works fine with the engine built from [v1.1.0](https://github.com/tpm2-software/tpm2-tss-engine/releases/tag/v1.1.0).

**Comment by AndreasFuchsSIT** [comment]
@rshearman Could you say anything about this ?

**Comment by AndreasFuchsSIT** [comment]
@CIPop can you confirm that latest master solves the issue for you ?

**Comment by CIPop** [comment]
Thank you for the fix! We'll try it out and report back.

**Comment by AndreasFuchsSIT** [comment]
Very well.
I'll keep this bug open until you report back end then will continue the release process.

**Comment by AndreasFuchsSIT** [comment]
@CIPop Any news on this running ?
I'd like to see if we can get this out soon...

**Comment by CIPop** [comment]
Everything works as expected with latest (0c663c2abf46941d283d207237b51f421cde35a1)!
I have tested both RSA and EC certificates with the scenario above and the server accepts the connection in both cases.

Thank you again for the fix!
