### ISSUE TITLE
Requested 'tss2-esys >=2.3' but version of tss2-esys is <hash>

### ISSUE THREAD

**Issue by kugelman** [tpm2-software/tpm2-tss-engine#252]
Hi -- following the instructions in INSTALL.md, ./configure in this project fails with

```
checking for TSS2_ESYS... no
configure: error: Package requirements (tss2-esys >= 2.3) were not met:

Requested 'tss2-esys >= 2.3' but version of tss2-esys is c12d2bc
You may find new versions of tss2-esys at https://github.com/tpm2-software/tpm2-tss

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables TSS2_ESYS_CFLAGS
and TSS2_ESYS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

It looks like c12d2bc is the current head of Master in tpm2-tss, I'm guessing I need to specify a specific branch or tag to clone from instead. Not sure if this is a documentation issue or if cloning tpm2-tss from master is actually supposed to work.

**Comment by williamcroberts** [comment]
Ahh the instructions have a shallow clone in them with the option `--depth=1`. Remove that option and re-clone, build and re-install and it will get the proper version information.
