### ISSUE TITLE
Sending authentication data with engine requests

### ISSUE THREAD

**Issue by xlandrexl** [tpm2-software/tpm2-tss-engine#256]
Hello, 

Is it possible to send authentication data with the requests? (For example, if the owner hierarchy has a password). I know it is mentioned in page, but I can not find any documentation. 

Thanks

**Comment by williamcroberts** [comment]
Look at `openssl.conf.sample` it has support for setting OWNER or parent key authorization if needed.
The downside is it's required to be in an openssl conf file. Perhaps the Openssl conf file could be a generated here doc.
