### ISSUE TITLE
How to: load tpm2tss engine in openssl

### ISSUE THREAD

**Issue by marco99asr** [tpm2-software/tpm2-tss-engine#258]
Hi 
im tryng to add tpm2tss engine to openssl

root:/home# openssl engine -t -c
(rdrand) Intel RDRAND engine
 [RAND]
     [ available ]
(dynamic) Dynamic engine loading support
     [ unavailable ]
     

root:/home# openssl engine tpm2tss -t -c
(tpm2tss) TPM2-TSS engine for OpenSSL
 [RSA, RAND]
     [ available ]

Can someone help me ?

**Comment by williamcroberts** [comment]
That's a very vague question:
1. How did you install it?
2. What's your distro?
3. Did you follow https://github.com/tpm2-software/tpm2-tss-engine/blob/master/INSTALL.md?

**Comment by marco99asr** [comment]
https://github.com/eclipse/mosquitto/issues/2646

**Comment by williamcroberts** [comment]
`¯\_(ツ)_/¯`
I have no idea

**Comment by AndreasFuchsTPM** [comment]
From the config in the linked ticket, I'd assume something like
```
tls_engine tpm2tss
tls_keyform engine
```

Does this work / not work ?
