### ISSUE TITLE
openssl.conf.sample is not working as intended (since OpenSSL_1_1_0-pre1)

### ISSUE THREAD

**Issue by wxleong** [tpm2-software/tpm2-tss-engine#260]
In `openssl.conf.sample`, the option `ECDSA` has been removed since OpenSSL_1_1_0-pre1 in this [commit](https://github.com/openssl/openssl/commit/1eb97c3ecd5a9c7faa9436d506735be0bd7c3b4b#diff-14dfb541c246d67b67ccfa6f47883b4a7517a38bfba187941df0b6468ab815a7L110). 

It seems harmless, but if the [parser](https://github.com/openssl/openssl/blob/OpenSSL_1_1_0-pre1/crypto/engine/eng_cnf.c#L91) encountered an invalid option, it will exit silently. Meaning, everything come after the line `default_algorithms = RSA,ECDSA` are ignored.

Maybe to cleanup the `openssl.conf.sample` so user will not run into trouble such as pondering why `SET_TCTI` does not work.

**Comment by AndreasFuchsTPM** [comment]
Would you mind sending a PR on this ?

**Comment by wxleong** [comment]
https://github.com/tpm2-software/tpm2-tss-engine/pull/265
