### ISSUE TITLE
Installing with openssl >= 3.0 errors

### ISSUE THREAD

**Issue by VVARELA15** [tpm2-software/tpm2-tss-engine#262]
I am installing tpm2-tss-engine on a pi 4. I have openssl 3.2.0 installed. I am getting the errors below when I attempt to make:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/11048844/200069368-e7d2cdc3-066e-41f9-9df1-460da4d578c8.png">

When I make using openssl version1.1.1n I get the following errors:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/11048844/200075774-b6fb1967-1a88-41f5-b34d-99959906d5cf.png">

I would rather install using openssl 3.0. How do I install using Openssl >= 3.0?

**Comment by VVARELA15** [comment]
> Use the tpm2-provider project for OSSL 3+, it can be found here:
> 
> * https://github.com/tpm2-software/tpm2-provder

That link gives me a 404 error. Should I use tpm2-provider instead of tpm2-tss-engine?

**Comment by williamcroberts** [comment]
> > Use the tpm2-provider project for OSSL 3+, it can be found here:
> > 
> > * https://github.com/tpm2-software/tpm2-provder
> 
> That link gives me a 404 error. Should I use tpm2-provider instead of tpm2-tss-engine?

Whoops, sorry I gave you the wrong name for the project and I even typo'd it! Please try project tpm2-openssl for the provider: 
  - https://github.com/tpm2-software/tpm2-openssl
