### ISSUE TITLE
Persistent key pair create, delete and retrieve in TPM2 using tss2 software stack

### ISSUE THREAD

**Issue by sachingole** [tpm2-software/tpm2-tss-engine#38]
HI All,

Following is configuration.
Raspberry Pi 3 + Linux TPM2 and TSS2 software stack.

1. Using TPM2 and TSS2 software generated RSA keypair and self signed certificate
```
 tpm2tss-genkey -a rsa rsa.tss
 openssl req -new -x509 -engine tpm2tss -key rsa.tss  -keyform engine  -out rsa.crt
```

2. create CSR for above generated key
` openssl req -new -engine tpm2tss -keyform engine -out rsa.csr -key rsa.tss
`
csr can be used to get client certificate.

**Q1. When RPi rebooted key is not persistent, How to store key pair and retrieve public key. ?**
**Q2. Following command gives public key for provided key blob, is this right command ?**

Getting Public key out from tpm2 module :-
` openssl rsa -engine tpm2tss -inform engine -in rsa.tss -pubout -outform pem -out rsa.pub
`

**Q3. How to delete persistent stored key pair ?**

**Comment by GaelGuegan** [comment]
Q1. You can create a rsa key persistent  with tpm-tools : 
```shell
#!/bin/bash -eu

DIR=$(mktemp -d --tmpdir)
echo "Working in directory '$DIR'"
PARENT_CTX=${DIR}/primary_owner_key.ctx

echo "Generating primary key"
tpm2_createprimary -a o -g sha256 -G rsa -o ${PARENT_CTX}
echo "Generating RSA key pair"
TPM_RSA_PUBKEY=${DIR}/rsakey.pub
TPM_RSA_KEY=${DIR}/rsakey
# Create an RSA key pair
tpm2_create -C ${PARENT_CTX} -g sha256 -G rsa -u ${TPM_RSA_PUBKEY} -r ${TPM_RSA_KEY} -A sign\|decrypt\|fixedtpm\|fixedparent\|sensitivedataorigin\|userwithauth\|noda
RSA_CTX=${DIR}/rsakey.ctx
tpm2_load -C ${PARENT_CTX} -u ${TPM_RSA_PUBKEY} -r ${TPM_RSA_KEY} -o ${RSA_CTX}
# Made it persistent
tpm2_evictcontrol -a o -c ${RSA_CTX} -p 0x81010003

RSA_PUBKEY=${DIR}/rsa.pub
# Read the RSA public key in PEM format for OpenSSL
tpm2_readpublic -c 0x81010003 -o ${RSA_PUBKEY} -f pem

# Signature Example
echo "my data to sign" | tee message.txt
tpm2_sign -c 0x81010003 -G sha256 -m message.txt -f plain -s data.signed
echo "Data signed :"
cat data.signed
```

Q3. 
```shell
tpm2_evictcontrol -a o -c ${RSA_CTX} -p 0x81010003
```

**Comment by AndreasFuchsSIT** [comment]
@GaelGuegan Thanks for the answer and the original implementation !

One addition: We have an integration test performing exactly this usecase:
https://github.com/tpm2-software/tpm2-tss-engine/blob/master/test/rsasign_persistent.sh

**Comment by sachingole** [comment]
Any help on below error 
**ERROR: Tss2_Sys_Load(0x902) - tpm:warn(2.0): out of memory for object contexts
ERROR: Unable to run tpm2_load**

```
root@raspberrypi:/home/pi/testkey# tpm2_clear
skyproot@raspberrypi:/home/pi/testkey# tpm2_createprimary -a o -g sha256 -G rsa -o primary_owner_key.ctx
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
  raw: 0x30072
type:
  value: rsa
  raw: 0x1
exponent: 0x0
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
rsa: b6be3eddb60163129d3c94b30eab533443835b0b3a93e4fa9f65d9567bf735bcd63b06dbc2315d3e17428a4827a6d8dd6fd79fd6b698d6d259cc4bc98de43b70912b520bcf36b3b5f7653e76f25d81fce3f40da08d9485b6cb76585ca2cb4112ae34a00fb474e711119ee660d3c7b9a10fdbbac2d94b74caf6618ce135be0bf62950e4563be6d2e69d94799a09ce872aa0b548c4fdfccc2a589b830661a2d56705b95fb74c68ba733c2c891cdd0175fad7936300d12ec4bd1bb2f35c59132472b86224c0187ae38f51cf14ae5d96ce4a040607443cc0de6ba3b67a566cdae5bfbe16a74c48d78e34e370e365680fb4d0461bdf7580fd3ab6b237cf34cb0e4ac1
handle: 0x80000000
root@raspberrypi:/home/pi/testkey# tpm2_create -C primary_owner_key.ctx -g sha256 -G rsa -u rsakey.pub -r rsakey
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|decrypt|sign
  raw: 0x60072
type:
  value: rsa
  raw: 0x1
exponent: 0x0
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: null
  raw: 0x10
sym-mode:
  value: (null)
  raw: 0x0
sym-keybits: 0
rsa: 9cae6aaa268f02d221ac2eda0abebc31c9481cd3da030eace4ee3d4c1b58ecd2e31e6e565d59c207cb8b8c212292518bdc9626126075b7013e98435c01356cdf0abea4ce551c981da52d259dee9bf40884e664bc2956343433056ba25c8c4195d6644355158475890a7223116a4031787945bcb7b4768ba5e5ca334ce7489d1189854740074d15a5bc504819495adc0089516c235da2391c9883b8deb6592ebc3c4e827ba3c9d04047a4e3f5e52c0d58cc8141e8e20fa387c80d57a981e057884af966281b6534b83d831de6c2e53a6584cc68845302804570c1c64d3bb7c97c0b059df85d96853329831828ab87f3a41ebf6c15609e2b1abecc73fbfc7e7697
root@raspberrypi:/home/pi/testkey# 
root@raspberrypi:/home/pi/testkey# 
root@raspberrypi:/home/pi/testkey# tpm2_load -C primary_owner_key.ctx -u rsakey.pub -r rsakey -o rsakey.ctx
ERROR: Tss2_Sys_Load(0x902) - tpm:warn(2.0): out of memory for object contexts
ERROR: Unable to run tpm2_load
root@raspberrypi:/home/pi/testkey# 

```

**Comment by GaelGuegan** [comment]
Did you have installed tpm2-abrmd ?

If not i don't know

**Comment by AndreasFuchsSIT** [comment]
TPM can hold only 3 loaded objects in parallel.
Either use a resource-manager (tpm2-abrmd or /dev/tpmrm0) or flush your objects after use...
See `tpm2_flushcontext -T mssim -t` from the integration test...

**Comment by sachingole** [comment]
@GaelGuegan , Thanks, I have installed tpm2-abrmd now.
@AndreasFuchsSIT , Thank you. I can store key with following command.

tpm2_createprimary -a o -g sha256 -G rsa -o primary_owner_key.ctx
tpm2_create -C primary_owner_key.ctx -g sha256 -G rsa -u rsakey.pub -r rsakey
tpm2_load -C primary_owner_key.ctx -u rsakey.pub -r rsakey -o rsakey.ctx
tpm2_evictcontrol -a o -c rsakey.ctx -p 0x81010003
tpm2_readpublic -c 0x81010003 -o rsa.pub -f pem

**Comment by sachingole** [comment]
@GaelGuegan , Thanks, I have installed tpm2-abrmd now.
@AndreasFuchsSIT , Thank you. I can store key with following command.

tpm2_createprimary -a o -g sha256 -G rsa -o primary_owner_key.ctx
tpm2_create -C primary_owner_key.ctx -g sha256 -G rsa -u rsakey.pub -r rsakey
tpm2_load -C primary_owner_key.ctx -u rsakey.pub -r rsakey -o rsakey.ctx
tpm2_evictcontrol -a o -c rsakey.ctx -p 0x81010003
tpm2_readpublic -c 0x81010003 -o rsa.pub -f pem
