### ISSUE TITLE
Compilation with optimisation enabled breaks creation of ECDSA keys

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-tss-engine#42]
If I enable optimisation in GCC using the `-O1` compiler flag, the compilation seems to work fine, but the resulting `tpm2tss-genkey` binary fails to create ECC keys. I compile with GCC 8.2.1 on Arch Linux using the command sequence

```
git clone https://github.com/tpm2-software/tpm2-tss-engine.git
cd tpm2-tss-engine
./bootstrap
./configure CFLAGS='-O1' --enable-debug
make
```

Afterwards,
```
tpm_server &
export OPENSSL_ENGINES="$PWD/.libs"
./tpm2tss-genkey -a ecdsa -c nist_p256 mykey_ecdsa
```
results in
```
Initializing
Setting owner auth to empty auth.
GenKey for ecdsa.
Establishing connection with TPM.
WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-default.so 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-tabrmd.so 
ERROR:tcti:src/tss2-tcti/tcti-device.c:319:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:83:tcti_from_init() TCTI init for function 0x7f852a3dab20 failed with a000a 
ERROR:tcti:src/tss2-tcti/tcti-device.c:319:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: No such file or directory 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:83:tcti_from_init() TCTI init for function 0x7f852a3dab20 failed with a000a 
Creating primary key under owner.
Generating the ECC key inside the TPM.
Generated the ECC key inside the TPM.
Error: Generating key failed
Key could not be generated.
```
while
```
./tpm2tss-genkey -a rsa -s 2048 mykey_rsa
```
still works fine:
```
Initializing
Setting owner auth to empty auth.
Generating RSA key for 2048 bits keysize.
Establishing connection with TPM.
WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-default.so 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-tabrmd.so 
ERROR:tcti:src/tss2-tcti/tcti-device.c:319:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:83:tcti_from_init() TCTI init for function 0x7f760b707b20 failed with a000a 
ERROR:tcti:src/tss2-tcti/tcti-device.c:319:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: No such file or directory 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:83:tcti_from_init() TCTI init for function 0x7f760b707b20 failed with a000a 
Creating primary key under owner.
Generating the RSA key inside the TPM.
Generated the RSA key inside the TPM.
```
If I disable optimisations, i.e. use
```
./configure CFLAGS='' --enable-debug
```
in the above command sequence, both keys are created successfully. The command output stays the same, apart from missing the last two error messages for the creation of the ECC key.

Usually turning on `-O1` should not break functionality (Arch even uses the more aggressive `-O2` for packaging by default). I suspect there is some undefined behaviour in [`tpm2-tss-engine-ecc.c`](https://github.com/tpm2-software/tpm2-tss-engine/blob/master/src/tpm2-tss-engine-ecc.c) that causes problems when being "optimised away" in an unexpected manner.

**Comment by diabonas** [comment]
Some more investigation reveals that the problem seems to be related to the static variable [`ec_key_app_data`](https://github.com/tpm2-software/tpm2-tss-engine/blob/2cc72e5fb58a14bc284f1e90df6a44aafc75d8ab/src/tpm2-tss-engine-ecc.c#L44): in [`init_ecc`](https://github.com/tpm2-software/tpm2-tss-engine/blob/2cc72e5fb58a14bc284f1e90df6a44aafc75d8ab/src/tpm2-tss-engine-ecc.c#L538), it gets initialised to `1`, but somehow during execution it changes to `-2147483647`, I do not know how. This causes [`EC_KEY_get_ex_data`](https://github.com/tpm2-software/tpm2-tss-engine/blob/2cc72e5fb58a14bc284f1e90df6a44aafc75d8ab/src/tpm2-tss-engine-ecc.c#L369) to return `NULL`, which makes [`populate_ecc` return unsucessfully](https://github.com/tpm2-software/tpm2-tss-engine/blob/2cc72e5fb58a14bc284f1e90df6a44aafc75d8ab/src/tpm2-tss-engine-ecc.c#L237).

Curiously, changing the type of from `ec_key_app_data` from `int` to `short` causes this problem to disappear, but this is obviously not the correct solution: apparently the memory area of `ec_key_app_data` gets partly overwritten somewhere, which points to a memory overflow of some kind.

**Comment by diabonas** [comment]
I found the culprit: according to [the OpenSSL documentation](https://www.openssl.org/docs/man1.1.0/crypto/ERR_load_strings.html), `ERR_STRING_DATA` arrays need to be terminated with a `{0,0}` element. This was not done for [`TPM2TSS_f`](https://github.com/tpm2-software/tpm2-tss-engine/blob/2cc72e5fb58a14bc284f1e90df6a44aafc75d8ab/src/tpm2-tss-engine-err.c#L45) and [`TPM2TSS_r`](https://github.com/tpm2-software/tpm2-tss-engine/blob/2cc72e5fb58a14bc284f1e90df6a44aafc75d8ab/src/tpm2-tss-engine-err.c#L71), causing the OpenSSL function [`ERR_load_strings`](https://github.com/tpm2-software/tpm2-tss-engine/blob/2cc72e5fb58a14bc284f1e90df6a44aafc75d8ab/src/tpm2-tss-engine-err.c#L115) to overwrite into the directly adjacent memory of `ec_key_app_data`. I have prepared #43 to fix the problem.

**Comment by JuergenReppSIT** [comment]
your PR will be reviewed next week. Thanks.
