### ISSUE TITLE
passphrase on keys

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss-engine#5]
I've just run through the examples from the README. Very cool. One issue I'm having is that the openssl command line tools prompt for a password to be set when the key is created and when it is subsequently loaded. I tried setting a passphrase here but it never works when I go to use my keys. Is this a known issue? Does this passphrase map to a TPM2 authorization value or is it just an openssl thing?

**Comment by AndreasFuchsSIT** [comment]
The passphrase maps to the TPM2 authvalue.

I am a little confused, because the tests actually use the passphrases, see e.g. https://github.com/tpm2-software/tpm2-tss-engine/blob/master/test/rsasign.sh

Could you verify that make check runs, or maybe follows what's written there instead of the README ?

**Comment by flihp** [comment]
I hadn't run any of the tests but I've got 3 passes and 3 fails. It looks like all 6 are failing though based on the output / log file. A closer look and some of the tests will produce successful output even if the test is unable to load the engine. Something is wrong with my setup but not quite sure what yet. Will report back details when I have them.

**Comment by flihp** [comment]
Well I found one problem: I keep having to switch between OSSL 1.1 and 1.0.X headers for compatibility with different projects and I had the 1.0.x headers installed. Seems the engine only works with 1.1.x for me. Could also be that my local openssl command line utilities are trying to load the 1.1.x libraries while I've built the engine against the 1.0.2 ones.

99% certain this has nothing to do with the password thing though. Just why I spent the last hour reading strace logs :smile:

**Comment by flihp** [comment]
Mystery solved: My problem was that I had created a key that had no password set. The point of confusion is that all of the `openssl` command were prompting me for a password and they only do this if a password has been set ... except when using this engine.

I guess there's no way for openssl to know if an auth value has been set and so you always display the prompt?

**Comment by AndreasFuchsSIT** [comment]
openssl: That's weird, since the travis also works with the OpenSSL_1_0_2-stable branch of OpenSSL. Could you elaborate on that ?
password: You never know if a password is empty or not for the TPM. So yeah. I'll document this better.

**Comment by flihp** [comment]
I did this:
1) built tpm2tss engine against v1.0.2 headers
2) used `openssl` command linked against v1.1.0 to load tpm2tss engine
3) got error about version mismatch
That seems like expected behavior to me.

**Comment by AndreasFuchsSIT** [comment]
Agreed... ;-)
