### ISSUE TITLE
Specify tpm-tools version

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss-engine#67]
Travis is failing due, most probably because we allways pull tpm2-tools master.
Switch to a stable branch instead for the moment...

**Comment by AndreasFuchsSIT** [comment]
TBD on next tpm2-tools release since current stable lacks needed tpm2_flushcontext

**Comment by AndreasFuchsSIT** [comment]
Once https://github.com/tpm2-software/tpm2-tools/issues/1452 is closed, we can do something here

**Comment by joholl** [comment]
We should probably consider porting to tpm2-tools 4.x now that it is released.

**Comment by diabonas** [comment]
@joholl See #142 for a PR that does that.

**Comment by joholl** [comment]
Oh, I did not see that, my bad. Thanks for pointing out @diabonas!

**Comment by AndreasFuchsSIT** [comment]
Fixed via #142
