### ISSUE TITLE
cmocka

### ISSUE THREAD

**Issue by zbsarashki** [tpm2-software/tpm2-tss-engine#81]
Hi, are the unit tests enabled by default? Is there an option to disable the tests in configure thanks, Babak

**Comment by AndreasFuchsSIT** [comment]
Yes, since it's only 1 so far, there is no switch ?

I guess you'd like to disable them to save the cmocka build dependency ?

**Comment by zbsarashki** [comment]
Hi Andreas,

Added a switch to disable as I don't have cmocka.

Thanks,
babak

**Comment by AndreasFuchsSIT** [comment]
Cool, mind to share this in a pull request ?

**Comment by AndreasFuchsSIT** [comment]
see #84

**Comment by AndreasFuchsSIT** [comment]
Solved in #84
