### ISSUE TITLE
Error generate .CSR

### ISSUE THREAD

**Issue by roberto497** [tpm2-software/tpm2-tss-engine#92]
After reinstall tpm2-tss with ./configure --prefix=/usr **--with-crypto=gcrypt**

The command that worked stopped working:
**openssl req -new -engine tpm2tss -keyform engine -out client.csr -key 0x81010003**

returns this error:
ERROR:esys:src/tss2-esys/esys_iutil.c:780:iesys_decrypt_param() Invalid length encrypted response. ErrorCode (0x0007000b) 
ERROR:esys:src/tss2-esys/esys_iutil.c:1403:iesys_check_response() Error: while decrypting parameter. ErrorCode (0x0007000b) 
ERROR:esys:src/tss2-esys/api/Esys_ReadPublic.c:341:Esys_ReadPublic_Finish() Error: check response ErrorCode (0x0007000b) 
ERROR:esys:src/tss2-esys/api/Esys_ReadPublic.c:108:Esys_ReadPublic() Esys Finish ErrorCode (0x0007000b) 
cannot load Private Key from engine
139980224664000:error:8007006F:tpm2-tss-engine:tpm2tss_tpm2data_readtpm:Some unknown error occured:src/tpm2-tss-engine-common.c:303:
139980224664000:error:80064064:tpm2-tss-engine:loadkey:Failed to read TPM2 data:src/tpm2-tss-engine.c:191:
139980224664000:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:../crypto/engine/eng_pkey.c:78:
unable to load Private Key

Any suggestion?

**Comment by AndreasFuchsSIT** [comment]
Looks like a tpm2-tss error. Can you `--enable-integration` and `make check TESTS=test/integration/esys-tr-fromTpmPublic-key` on the tpm2-tss ?
And which version of tpm2-tss are you running ?

**Comment by roberto497** [comment]
tpm2-tss 2.2.0

**Comment by roberto497** [comment]
Solved, update the version and works
