### ISSUE TITLE
Missing dependency: expect

### ISSUE THREAD

**Issue by DomiNic5787** [tpm2-software/tpm2-tss-engine#99]
`expect` is used in test [rsasign_persistent_emptyauth.sh](https://github.com/tpm2-software/tpm2-tss-engine/blob/master/test/rsasign_persistent_emptyauth.sh), but not mentioned in the [INSTALL.md](https://github.com/tpm2-software/tpm2-tss-engine/blob/master/INSTALL.md) dependencies list.

**Comment by AndreasFuchsSIT** [comment]
Correct.
Also replace ronn with pandoc and tpm2-tss >2.0.0 with tpm2-tss >=2.2.2
